FROM nginx
#man kan vælge mange settings for nginx men man behøver bare gøre dette
#FROM henter fra dockerhub hvis man ikke allerede har et image af det

COPY . /usr/share/nginx/html
#første punktum betyder tag alt i samme mappe som dockerfilem
#pathen er hvor den ligger i containeren, når containeren starter kigger den u den folder
